<a href="https://colab.research.google.com/github/nehalmohamed2/Python-Practice/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
#list ==difrent data
#array  fixed date ---flot --
#can change number for string
#array -----افضل -----smal space + faster preforomec
#voctore----row or coulme
#MAtraics-----colume * row

list =[1,2,3,4,5.8,'a']
print(list)
print(np.array(list))

[1, 2, 3, 4, 5.8, 'a']
['1' '2' '3' '4' '5.8' 'a']


In [ ]:
l = [[1,2,3]  ,  [4,5,6]]
print(l)

[[1, 2, 3], [4, 5, 6]]


In [ ]:
m =np.array(l)
print(m)

[[1 2 3]
 [4 5 6]]


In [ ]:
#shaps ----returen the number of row and coulme
m.shape

(2, 3)

In [ ]:
#range----return
#indax + steps

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# rand -------creat an array
np.random.rand(2,3)
#np.random.seed(42)

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452]])

In [ ]:
arr = np.array ( [ [1,2,3,4] ,[5,6,7,8] ] )
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(np.median(arr))

8
1
4.5
4.5


In [ ]:
z = np.array ( [ [1,2,3,4] ,[5,6,7,8] ] )
z[0] # apper frist list
z[1]
z[0,0]
z[1,1]

np.int64(6)